name: Speedrun like Dream
version 1.16.4
description: increase the rate of pearl drops from bartering and rod drops from blazes to an incredible amount. also auto-time from beginning of player spawn to time player goes through portal

